-- Clean configuration seed. Admin is DISABLED until initialized. No customers/orders/payments.

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `sys_dept` DISABLE KEYS */;
INSERT INTO `sys_dept` (`dept_id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (100,0,'0','总公司',0,'','','','0','0','admin','2026-09-16 13:01:05','',NULL);
INSERT INTO `sys_dept` (`dept_id`, `parent_id`, `ancestors`, `dept_name`, `order_num`, `leader`, `phone`, `email`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (101,100,'0,100','默认部门',1,'','','','0','0','admin','2026-09-16 13:01:05','',NULL);
/*!40000 ALTER TABLE `sys_dept` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_post` DISABLE KEYS */;
INSERT INTO `sys_post` (`post_id`, `post_code`, `post_name`, `post_sort`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1,'admin','管理员',1,'0','admin','2026-09-16 13:01:06','',NULL,'');
/*!40000 ALTER TABLE `sys_post` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_user` DISABLE KEYS */;
INSERT INTO `sys_user` (`user_id`, `dept_id`, `user_name`, `nick_name`, `user_type`, `email`, `phonenumber`, `sex`, `avatar`, `password`, `status`, `del_flag`, `login_ip`, `login_date`, `pwd_update_date`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1,101,'admin','Administrator','00','','','1','','!UNINITIALIZED!','1','0','',NULL,'2026-09-16 13:01:06','admin','2026-09-16 13:01:06','system','2026-09-16 13:01:12','Set a private password before enabling');
/*!40000 ALTER TABLE `sys_user` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_user_post` DISABLE KEYS */;
INSERT INTO `sys_user_post` (`user_id`, `post_id`) VALUES (1,1);
/*!40000 ALTER TABLE `sys_user_post` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_user_role` DISABLE KEYS */;
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (1,1);
/*!40000 ALTER TABLE `sys_user_role` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_role` DISABLE KEYS */;
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1,'超级管理员','admin',1,'1',1,1,'0','0','admin','2026-09-16 13:01:06','',NULL,'超级管理员');
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (100,'Club只读','club_readonly',20,'1',1,1,'0','0','system','2026-09-16 13:03:03','',NULL,'品奢电竞全域只读验收角色');
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (101,'Club客服','club_customer_service',21,'1',1,1,'0','0','system','2026-09-16 13:03:03','',NULL,'客服只读订单与售后，不含退款和财务审批');
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (102,'Club运营','club_operations',22,'1',1,1,'0','0','system','2026-09-16 13:03:03','',NULL,'商品店铺内容配置运营，不含财务和用户角色修改');
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (103,'Club审核','club_reviewer',23,'1',1,1,'0','0','system','2026-09-16 13:03:03','',NULL,'实名入驻与售后仲裁验收角色');
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (104,'Club财务','club_finance',24,'1',1,1,'0','0','system','2026-09-16 13:03:03','',NULL,'钱包提现充值结算与退款资金审核');
INSERT INTO `sys_role` (`role_id`, `role_name`, `role_key`, `role_sort`, `data_scope`, `menu_check_strictly`, `dept_check_strictly`, `status`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (105,'Club管理员','club_admin',25,'1',1,1,'0','0','system','2026-09-16 13:03:03','',NULL,'品奢电竞业务全权限，不含若依无关模块');
/*!40000 ALTER TABLE `sys_role` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_role_dept` DISABLE KEYS */;
/*!40000 ALTER TABLE `sys_role_dept` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_role_menu` DISABLE KEYS */;
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2101);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2102);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2103);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2104);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2105);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2106);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2107);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2108);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2109);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2110);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2111);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2112);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2113);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2114);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2115);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2116);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2117);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2118);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2119);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2120);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2121);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2122);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2123);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2124);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2125);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2126);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2127);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2128);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2129);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2130);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2131);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2132);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2133);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2134);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (100,2213);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2102);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2103);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2104);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2105);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2106);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2116);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2121);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2122);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2128);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2130);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2131);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2132);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (101,2213);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2103);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2104);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2110);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2111);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2113);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2114);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2115);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2116);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2117);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2118);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2122);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2127);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2130);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2131);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2134);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2202);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2203);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2208);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2210);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2211);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2214);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2215);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2216);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2220);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2221);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2224);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (102,2225);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2105);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2106);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2107);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2108);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2121);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2128);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2132);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2133);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2205);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2206);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2212);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2213);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (103,2223);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2105);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2106);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2109);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2119);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2120);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2121);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2123);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2128);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2129);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2132);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2133);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2212);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2213);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2217);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2219);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (104,2223);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2100);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2101);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2102);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2103);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2104);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2105);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2106);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2107);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2108);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2109);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2110);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2111);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2112);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2113);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2114);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2115);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2116);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2117);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2118);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2119);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2120);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2121);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2122);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2123);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2124);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2125);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2126);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2127);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2128);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2129);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2130);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2131);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2132);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2133);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2134);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2201);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2202);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2203);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2204);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2205);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2206);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2207);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2208);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2209);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2210);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2211);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2212);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2213);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2214);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2215);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2216);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2217);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2218);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2219);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2220);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2221);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2222);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2223);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2224);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2225);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2226);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES (105,2227);
/*!40000 ALTER TABLE `sys_role_menu` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_menu` DISABLE KEYS */;
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2100,'俱乐部管理',0,1,'club',NULL,NULL,'',1,0,'M','0','0','','shopping','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','品奢电竞业务管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2101,'数据总览',2100,1,'dashboard','club/dashboard/index',NULL,'ClubDashboard',1,0,'C','0','0','club:dashboard:list','dashboard','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','业务数据总览');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2102,'顾客管理',2100,2,'users','club/manage/index','{\"entity\":\"users\"}','ClubUsers',1,1,'C','0','0','club:user:list','user','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','小程序用户管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2103,'店铺管理',2100,3,'shops','club/manage/index','{\"entity\":\"shops\"}','ClubShops',1,1,'C','1','0','club:shop:list','shopping','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','店铺管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2104,'商品管理',2100,4,'products','club/manage/index','{\"entity\":\"products\"}','ClubProducts',1,1,'C','0','0','club:product:list','shopping','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','商品服务管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2105,'订单管理',2100,5,'orders','club/manage/index','{\"entity\":\"orders\"}','ClubOrders',1,1,'C','0','0','club:order:list','clipboard','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','订单管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2106,'支付记录',2100,6,'payments','club/manage/index','{\"entity\":\"payments\"}','ClubPayments',1,1,'C','0','0','club:order:list','money','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','模拟支付记录');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2107,'打手审核',2100,7,'applications','club/manage/index','{\"entity\":\"applications\"}','ClubApplications',1,1,'C','0','0','club:application:list','peoples','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','打手商家入驻审核');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2108,'实名审核',2100,8,'identities','club/manage/index','{\"entity\":\"identities\"}','ClubIdentities',1,1,'C','1','0','club:identity:list','validCode','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','实名认证审核');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2109,'提现打款',2100,9,'withdrawals','club/manage/index','{\"entity\":\"withdrawals\"}','ClubWithdrawals',1,1,'C','0','0','club:finance:list','money','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','提现审核');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2110,'宣传内容',2100,10,'content','club/manage/index','{\"entity\":\"content\"}','ClubContent',1,1,'C','0','0','club:content:list','edit','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','宣传图片字体资讯文档管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2111,'评价管理',2100,11,'reviews','club/manage/index','{\"entity\":\"reviews\"}','ClubReviews',1,1,'C','0','0','club:content:list','rate','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','评价管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2112,'优惠券管理',2100,12,'coupons','club/manage/index','{\"entity\":\"coupons\"}','ClubCoupons',1,1,'C','0','0','club:config:list','money','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','优惠券管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2113,'消息管理',2100,13,'messages','club/manage/index','{\"entity\":\"messages\"}','ClubMessages',1,1,'C','0','0','club:content:list','message','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','消息管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2114,'打手管理',2100,14,'players','club/manage/index','{\"entity\":\"players\"}','ClubPlayers',1,1,'C','0','0','club:player:list','peoples','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','陪玩公开资料管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2115,'分类管理',2100,15,'categories','club/manage/index','{\"entity\":\"categories\"}','ClubCategories',1,1,'C','0','0','club:content:list','tree','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','商品分类管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2116,'规格管理',2100,16,'skus','club/manage/index','{\"entity\":\"skus\"}','ClubSkus',1,1,'C','1','0','club:product:list','list','system','2026-09-16 13:01:12','system','2026-09-16 13:01:12','商品规格与库存管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2117,'优惠券发放',2100,13,'coupon-issues','club/manage/index','{\"entity\":\"couponIssues\"}','ClubCouponIssues',1,1,'C','0','0','club:coupon:list','money','system','2026-09-16 13:02:53','',NULL,'向指定用户发放优惠券');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2118,'钱包总览',2100,14,'wallets','club/manage/index','{\"entity\":\"wallets\"}','ClubWallets',1,1,'C','0','0','club:coupon:list','money','system','2026-09-16 13:02:53','',NULL,'服务方钱包余额与累计数据');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2119,'钱包流水',2100,15,'wallet-records','club/manage/index','{\"entity\":\"walletRecords\"}','ClubWalletRecords',1,1,'C','1','0','club:wallet:list','list','system','2026-09-16 13:02:53','',NULL,'钱包资金流水');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2120,'订单结算',2100,16,'settlements','club/manage/index','{\"entity\":\"settlements\"}','ClubSettlements',1,1,'C','1','0','club:wallet:list','money','system','2026-09-16 13:02:53','',NULL,'订单收益与退款冲正');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2121,'订单状态记录',2100,17,'order-logs','club/manage/index','{\"entity\":\"orderLogs\"}','ClubOrderLogs',1,1,'C','0','0','club:order:list','log','system','2026-09-16 13:02:53','',NULL,'订单状态审计记录');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2122,'业务配置',2100,18,'business-config','club/manage/index','{\"entity\":\"businessConfig\"}','ClubBusinessConfig',1,1,'C','0','0','club:customer-service:list','system','system','2026-09-16 13:02:53','',NULL,'佣金比例和自动确认时间');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2123,'充值订单',2100,19,'recharge-orders','club/manage/index','{\"entity\":\"rechargeOrders\"}','ClubRechargeOrders',1,1,'C','0','0','club:withdrawal:list','money','system','2026-09-16 13:02:53','',NULL,'模拟充值订单与余额入账记录');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2124,'充值档位',2100,20,'recharge-tiers','club/manage/index','{\"entity\":\"rechargeTiers\"}','ClubRechargeTiers',1,1,'C','0','0','club:finance-config:list','money','system','2026-09-16 13:02:53','',NULL,'小程序模拟充值金额档位');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2125,'客服配置',2100,21,'customer-config','club/manage/index','{\"entity\":\"customerConfig\"}','ClubCustomerConfig',1,1,'C','0','0','club:finance-config:list','service','system','2026-09-16 13:02:53','',NULL,'小程序客服入口和二维码配置');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2126,'青少年设置',2100,22,'teen-settings','club/manage/index','{\"entity\":\"teenSettings\"}','ClubTeenSettings',1,1,'C','0','0','club:teen-config:list','lock','system','2026-09-16 13:02:53','',NULL,'仅查看用户青少年模式启用状态');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2127,'陪玩服务绑定',2100,23,'player-services','club/manage/index','{\"entity\":\"playerServices\"}','ClubPlayerServices',1,1,'C','0','0','club:player:list','list','system','2026-09-16 13:03:03','',NULL,'陪玩可承接商品与规格');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2128,'售后管理',2100,24,'aftersales','club/manage/index','{\"entity\":\"aftersales\"}','ClubAftersales',1,1,'C','0','0','club:aftersale:list','clipboard','system','2026-09-16 13:03:03','',NULL,'售后状态与审核');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2129,'退款追偿',2100,25,'receivables','club/manage/index','{\"entity\":\"receivables\"}','ClubReceivables',1,1,'C','0','0','club:receivable:list','money','system','2026-09-16 13:03:03','',NULL,'服务方退款追偿记录');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2130,'关注关系',2100,26,'follows','club/manage/index','{\"entity\":\"follows\"}','ClubFollows',1,1,'C','1','0','club:shop:list','star','system','2026-09-16 13:03:03','',NULL,'用户关注店铺关系');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2131,'收藏关系',2100,27,'favorites','club/manage/index','{\"entity\":\"favorites\"}','ClubFavorites',1,1,'C','1','0','club:product:list','star','system','2026-09-16 13:03:03','',NULL,'用户收藏商品关系');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2132,'支付审计',2100,28,'payment-audits','club/manage/index','{\"entity\":\"paymentAudits\"}','ClubPaymentAudits',1,1,'C','0','0','club:order:list','log','system','2026-09-16 13:03:03','',NULL,'模拟支付请求幂等审计');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2133,'管理审计',2100,29,'admin-audits','club/manage/index','{\"entity\":\"adminAudits\"}','ClubAdminAudits',1,1,'C','0','0','club:audit:list','log','system','2026-09-16 13:03:03','',NULL,'后台高风险操作审计');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2134,'首页功能入口',2100,30,'home-entries','club/manage/index','{\"entity\":\"homeEntries\"}','ClubHomeEntries',1,1,'C','0','0','club:content:list','tree','system','2026-09-16 13:03:07','',NULL,'首页功能入口与商品分类独立管理');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2201,'用户编辑',2102,1,'',NULL,NULL,'',1,0,'F','0','0','club:user:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2202,'店铺编辑',2103,1,'',NULL,NULL,'',1,0,'F','0','0','club:shop:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2203,'商品编辑',2104,1,'',NULL,NULL,'',1,0,'F','0','0','club:product:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2204,'订单操作',2105,1,'',NULL,NULL,'',1,0,'F','0','0','club:order:operate','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2205,'入驻审核',2107,1,'',NULL,NULL,'',1,0,'F','0','0','club:application:review','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2206,'实名审核',2108,1,'',NULL,NULL,'',1,0,'F','0','0','club:identity:review','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2207,'财务审核',2109,1,'',NULL,NULL,'',1,0,'F','0','0','club:finance:review','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2208,'内容编辑',2110,1,'',NULL,NULL,'',1,0,'F','0','0','club:content:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2209,'配置编辑',2112,1,'',NULL,NULL,'',1,0,'F','0','0','club:config:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2210,'规格编辑',2116,1,'',NULL,NULL,'',1,0,'F','0','0','club:product:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2211,'陪玩服务编辑',2127,1,'',NULL,NULL,'',1,0,'F','0','0','club:product:edit','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2212,'售后审核',2128,1,'',NULL,NULL,'',1,0,'F','0','0','club:aftersale:review','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2213,'订单详情',2105,2,'',NULL,NULL,'',1,0,'F','0','0','club:order:detail','#','system','2026-09-16 13:03:03','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2214,'首页入口编辑',2134,1,'',NULL,NULL,'',1,0,'F','0','0','club:content:edit','#','system','2026-09-16 13:03:07','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2215,'陪玩编辑',2114,1,'',NULL,NULL,'',1,0,'F','0','0','club:player:edit','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2216,'陪玩停用',2114,2,'',NULL,NULL,'',1,0,'F','0','0','club:player:disable','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2217,'提现审核',2123,1,'',NULL,NULL,'',1,0,'F','0','0','club:withdrawal:review','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2218,'财务配置编辑',2124,1,'',NULL,NULL,'',1,0,'F','0','0','club:finance-config:edit','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2219,'追偿手工核销',2129,1,'',NULL,NULL,'',1,0,'F','0','0','club:receivable:writeoff','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2220,'优惠券编辑',2117,1,'',NULL,NULL,'',1,0,'F','0','0','club:coupon:edit','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2221,'客服配置编辑',2122,1,'',NULL,NULL,'',1,0,'F','0','0','club:customer-service:edit','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2222,'青少年策略编辑',2126,1,'',NULL,NULL,'',1,0,'F','0','0','club:teen-config:edit','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2223,'管理审计详情',2133,1,'',NULL,NULL,'',1,0,'F','0','0','club:audit:detail','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2224,'商品停用',2104,2,'',NULL,NULL,'',1,0,'F','0','0','club:product:disable','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2225,'店铺停用',2103,2,'',NULL,NULL,'',1,0,'F','0','0','club:shop:disable','#','system','2026-09-16 13:03:24','',NULL,'');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2226,'实名敏感详情',2108,8,'',NULL,NULL,'',1,0,'F','0','0','club:identity:detail','#','system','2026-09-16 13:03:24','',NULL,'独立查看加密实名材料并留访问审计');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2227,'钱包余额调整',2118,9,'',NULL,NULL,'',1,0,'F','0','0','club:wallet:adjust','#','system','2026-09-16 13:03:25','',NULL,'独立财务权限：增加或扣减可用余额，必须写原因、流水和审计');
/*!40000 ALTER TABLE `sys_menu` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_dict_type` DISABLE KEYS */;
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1,'用户性别','sys_user_sex','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2,'菜单状态','sys_show_hide','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3,'系统开关','sys_normal_disable','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (6,'系统是否','sys_yes_no','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (10,'系统状态','sys_common_status','0','admin','2026-09-16 13:01:07','',NULL,'');
/*!40000 ALTER TABLE `sys_dict_type` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_dict_data` DISABLE KEYS */;
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1,1,'男','0','sys_user_sex','','','Y','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2,2,'女','1','sys_user_sex','','','N','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3,3,'未知','2','sys_user_sex','','','N','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (4,1,'显示','0','sys_show_hide','','primary','Y','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (5,2,'隐藏','1','sys_show_hide','','danger','N','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (6,1,'正常','0','sys_normal_disable','','primary','Y','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (7,2,'停用','1','sys_normal_disable','','danger','N','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (12,1,'是','Y','sys_yes_no','','primary','Y','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (13,2,'否','N','sys_yes_no','','danger','N','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (28,1,'成功','0','sys_common_status','','primary','N','0','admin','2026-09-16 13:01:07','',NULL,'');
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (29,2,'失败','1','sys_common_status','','danger','N','0','admin','2026-09-16 13:01:07','',NULL,'');
/*!40000 ALTER TABLE `sys_dict_data` ENABLE KEYS */;

/*!40000 ALTER TABLE `sys_config` DISABLE KEYS */;
INSERT INTO `sys_config` (`config_id`, `config_name`, `config_key`, `config_value`, `config_type`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1,'主框架页-默认皮肤样式名称','sys.index.skinName','skin-blue','Y','admin','2026-09-16 13:01:08','',NULL,'');
INSERT INTO `sys_config` (`config_id`, `config_name`, `config_key`, `config_value`, `config_type`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2,'用户管理-账号初始密码','sys.user.initPassword','123456','Y','admin','2026-09-16 13:01:08','',NULL,'');
INSERT INTO `sys_config` (`config_id`, `config_name`, `config_key`, `config_value`, `config_type`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3,'主框架页-侧边栏主题','sys.index.sideTheme','theme-dark','Y','admin','2026-09-16 13:01:08','',NULL,'');
INSERT INTO `sys_config` (`config_id`, `config_name`, `config_key`, `config_value`, `config_type`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (4,'账号自助-验证码开关','sys.account.captchaEnabled','true','Y','admin','2026-09-16 13:01:08','',NULL,'');
INSERT INTO `sys_config` (`config_id`, `config_name`, `config_key`, `config_value`, `config_type`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (5,'账号自助-是否开启用户注册功能','sys.account.registerUser','false','Y','admin','2026-09-16 13:01:08','',NULL,'');
/*!40000 ALTER TABLE `sys_config` ENABLE KEYS */;

/*!40000 ALTER TABLE `club_business_config` DISABLE KEYS */;
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('aftersale_protection_hours','24','订单完成后的售后保护期小时数',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('aftersale_provider_response_hours','24','服务方处理售后申请的小时数',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('auto_complete_hours','24','服务方标记完成后自动确认的小时数',NULL,'2026-09-16 13:02:52');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('platform_commission_rate','20.00','平台佣金百分比，服务方收入为订单实付金额减平台佣金',NULL,'2026-09-16 13:02:52');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('ranking_enabled','1','是否启用消费排行榜：1启用，0停用',NULL,'2026-09-16 13:02:53');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('ranking_limit','50','排行榜最多展示人数，范围1至100',NULL,'2026-09-16 13:02:53');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('ranking_mask_nickname','1','排行榜昵称是否脱敏：1脱敏，0完整显示',NULL,'2026-09-16 13:02:53');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('ranking_period','all','排行榜统计周期：all、month、week、day',NULL,'2026-09-16 13:02:53');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('recharge_enabled','false','是否启用模拟充值中心：1启用，0停用',NULL,'2026-09-16 13:05:36');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_allowed_end','22:00','青少年模式允许使用结束时间',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_allowed_start','06:00','青少年模式允许使用开始时间',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_block_balance_payment','1','青少年模式是否禁止余额支付',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_block_order','1','青少年模式是否禁止下单',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_block_recharge','1','青少年模式是否禁止充值',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_block_withdrawal','1','青少年模式是否禁止提现',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_content_scope','product,news,announcement,promotion,document,ranking','青少年模式允许展示的内容类型',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_daily_spend_limit','0','青少年模式每日消费上限，0表示不单独配置',NULL,'2026-09-16 13:03:02');
INSERT INTO `club_business_config` (`config_key`, `config_value`, `description`, `updated_by`, `updated_at`) VALUES ('teen_single_spend_limit','0','青少年模式单次消费上限，0表示不单独配置',NULL,'2026-09-16 13:03:02');
/*!40000 ALTER TABLE `club_business_config` ENABLE KEYS */;

/*!40000 ALTER TABLE `club_category` DISABLE KEYS */;
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (1,'service','在线客服','customer-cartoon','/static/images/operators/operator-01.webp','','all',1,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (2,'anchor','主播专区','mic','/static/images/operators/operator-02.webp','/pages/product/list?category=anchor&title=主播专区','all',2,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (3,'new','新单专区','sparkles','/static/images/operators/operator-03.webp','/pages/product/list?category=new&title=新单专区','all',3,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (4,'special','特惠清图','tag','/static/images/operators/operator-04.webp','/pages/product/list?category=special&title=特惠清图','all',4,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (5,'space','航天巴克','rocket','/static/images/operators/operator-05.webp','/pages/product/list?category=space&title=航天巴克','all',5,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (6,'prison','监狱保底','shield','/static/images/operators/operator-06.webp','/pages/product/list?category=prison&title=监狱保底','all',6,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (7,'guarantee','不出不结','shield-check','/static/images/operators/operator-07.webp','/pages/product/list?category=guarantee&title=不出不结','all',7,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (8,'fun','趣味单专区','smile','/static/images/operators/operator-08.webp','/pages/product/list?category=fun&title=趣味单专区','all',8,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (9,'hour','小时单专区','clock','/static/images/operators/operator-09.webp','/pages/product/list?category=hour&title=小时单专区','all',9,'active');
INSERT INTO `club_category` (`id`, `code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`) VALUES (10,'evac','连续撤离','navigation','/static/images/operators/operator-10.webp','/pages/product/list?category=evac&title=连续撤离','all',10,'active');
/*!40000 ALTER TABLE `club_category` ENABLE KEYS */;

/*!40000 ALTER TABLE `club_home_entry` DISABLE KEYS */;
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (1,'service','在线客服','customer-cartoon','/static/images/operators/operator-01.webp','','all',1,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (2,'anchor','主播专区','mic','/static/images/operators/operator-02.webp','/pages/product/list?category=anchor&title=主播专区','all',2,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (3,'new','新单专区','sparkles','/static/images/operators/operator-03.webp','/pages/product/list?category=new&title=新单专区','all',3,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (4,'special','特惠清图','tag','/static/images/operators/operator-04.webp','/pages/product/list?category=special&title=特惠清图','all',4,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (5,'space','航天巴克','rocket','/static/images/operators/operator-05.webp','/pages/product/list?category=space&title=航天巴克','all',5,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (6,'prison','监狱保底','shield','/static/images/operators/operator-06.webp','/pages/product/list?category=prison&title=监狱保底','all',6,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (7,'guarantee','不出不结','shield-check','/static/images/operators/operator-07.webp','/pages/product/list?category=guarantee&title=不出不结','all',7,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (8,'fun','趣味单专区','smile','/static/images/operators/operator-08.webp','/pages/product/list?category=fun&title=趣味单专区','all',8,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (9,'hour','小时单专区','clock','/static/images/operators/operator-09.webp','/pages/product/list?category=hour&title=小时单专区','all',9,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
INSERT INTO `club_home_entry` (`id`, `entry_code`, `name`, `icon`, `avatar_image`, `target_url`, `role_scope`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (10,'evac','连续撤离','navigation','/static/images/operators/operator-10.webp','/pages/product/list?category=evac&title=连续撤离','all',10,'active','2026-09-16 13:03:07','2026-09-16 13:03:07');
/*!40000 ALTER TABLE `club_home_entry` ENABLE KEYS */;

/*!40000 ALTER TABLE `club_schema_history` DISABLE KEYS */;
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_p0','品奢电竞P0三端功能闭环','','2026-09-16 13:03:06','system',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_p0p1_v2','追偿回收、角色隔离、权限域与迁移审计字段','UNVERIFIED','2026-09-16 13:03:24','root@localhost',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_p1','P1关联闭环：真实小程序码、服务端试算、分页、提现/入驻/实名进度','','2026-09-16 13:03:07','system',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_p2_closure','经验等级、协议版本及资料入口闭环','UNVERIFIED','2026-09-16 13:03:24','root@localhost',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_usability','下单数量、关单及操作展示修复；新增实名独立详情权限','UNVERIFIED','2026-09-16 13:03:24','root@localhost',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_wallet_navigation','钱包调整按钮归属钱包总览','UNVERIFIED','2026-09-16 13:03:26','root@localhost',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260903_wallet_voice','钱包调整独立权限和幂等记录；流水并入钱包总览','UNVERIFIED','2026-09-16 13:03:26','root@localhost',1,0);
INSERT INTO `club_schema_history` (`version_no`, `description`, `checksum`, `installed_at`, `installed_by`, `success`, `execution_time_ms`) VALUES ('20260904_wechat_pay','微信支付APIv3小程序支付元数据','','2026-09-16 13:03:26','system',1,0);
/*!40000 ALTER TABLE `club_schema_history` ENABLE KEYS */;

/*!40000 ALTER TABLE `club_content` DISABLE KEYS */;
INSERT INTO `club_content` (`id`, `content_type`, `scene`, `title`, `subtitle`, `image`, `body_text`, `target_url`, `popup_enabled`, `start_at`, `end_at`, `style_json`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (1,'document','merchant-agreement','送给每一位老板的权益','服务规则请仔细阅读','','一、申请人应提供真实、准确、完整的主体及联系方式。\n二、平台审核通过后方可建立商家身份，商家与陪玩身份互斥。\n三、商品、价格、库存和服务说明必须真实有效。\n四、订单履约、售后、退款、结算和佣金以平台有效规则及订单记录为准。\n五、提交申请时系统记录协议版本和同意时间。','',0,NULL,NULL,NULL,0,'active','2026-09-16 13:01:09','2026-09-16 13:01:12');
INSERT INTO `club_content` (`id`, `content_type`, `scene`, `title`, `subtitle`, `image`, `body_text`, `target_url`, `popup_enabled`, `start_at`, `end_at`, `style_json`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (6,'document','about','关于我们','品奢电竞','','我们专注于提供清晰、可靠的线上娱乐服务体验。','',0,NULL,NULL,'{}',1,'active','2026-09-16 13:01:12','2026-09-16 13:01:12');
INSERT INTO `club_content` (`id`, `content_type`, `scene`, `title`, `subtitle`, `image`, `body_text`, `target_url`, `popup_enabled`, `start_at`, `end_at`, `style_json`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (7,'document','agreement','用户协议','用户服务协议','','品奢电竞用户服务协议\n版本日期：2026年9月10日；生效日期：本协议正式公布之日。\n一、运营主体与联系\n品奢电竞小程序由绵阳市涪城区品奢电竞科技网咖(个人独资)运营。客服、投诉及账号事项联系邮箱：m19915375856@163.com，您也可以通过小程序内在线客服联系。请认真阅读年龄限制、服务内容、支付退款及争议处理条款，充分理解后决定是否接受。\n二、服务对象与账号\n本平台仅面向年满18周岁的人员提供服务。购买服务的用户和申请成为陪玩服务人员的人员均应年满18周岁，未成年人不得注册、购买或提供服务。\n您应提供真实、准确、有效的账号及履约信息，不得冒用身份、出租出借账号或协助未成年人绕过限制。年龄声明不等于平台已对所有用户完成身份核验；在身份认证及服务人员审核场景，平台将按相应规则审核必要资料。\n账号安全及履约所需信息按隐私政策和具体授权提示处理。请勿向他人提供登录密码、验证码或支付密码。\n三、服务与订单\n平台提供商品页面明确说明的线上游戏陪玩等服务。服务内容、时长、规格、价格、负责服务人员及其他约定，以您下单确认的商品说明和订单为准。平台及服务人员作出的明确承诺应依法履行；除明确约定外，不当然保证游戏胜负、排名等结果。\n下单前请核对内容，填写准确的游戏ID、昵称和有效联系方式。付款不代表服务已经实际开始，服务开始应结合约定、实际履行及订单记录确定。未经您同意，不得擅自更改服务内容、任意加价或降低质量。无法按约服务时，平台应协助处理。\n四、支付与余额\n请通过平台提供的正规渠道支付，金额及优惠以订单展示为准。如使用充值或余额功能，请先核对充值金额、赠送条件和适用范围。余额不是理财产品，不承诺收益。\n未消费充值款可联系客服申请核实处理。赠送权益结合已明确告知的规则处理，不得排除法定权利。\n五、取消与退款\n服务开始前：可从订单售后入口或联系客服申请退款，经核实尚未实际开始服务的，退还该订单实际支付款项。\n服务开始后或正在服务中：请联系在线客服，提供订单编号、原因及必要记录。平台结合订单约定、已履行服务和责任情况处理，可包括继续履行、补救或依法退款，不实行开始后一律不退款。\n服务完成后：如存在未按约履行、质量问题或其他争议，仍可申请售后，不因订单显示已完成而丧失法定权利。\n因平台或服务人员原因无法履约的，不得无理拒绝或拖延处理。退款审核同意不等于资金已到账，以支付渠道或账户记录为准；异常时平台协助核查。退款原则上按原支付方式退回，确需其他方式应事先说明并取得确认。\n六、行为规范\n双方应文明沟通，不得实施骚扰、辱骂、歧视、诈骗、赌博、色情交易、恶意刷单或侵犯他人权益的行为。不得要求提供与正常服务无关的游戏账号密码、支付密码等，不得使用外挂或要求实施违法及违反游戏规则的行为。\n平台可对涉嫌违规行为核实并采取必要限制措施，同时提供申诉渠道。限制账号不免除未完成订单、资金及售后的处理责任。\n七、评价、收益及提现\n用户可对真实订单客观评价，不得发布虚假信息或泄露他人隐私。平台不得仅因评价不利而无正当理由删除真实评价。\n服务人员收益、结算和提现条件以事先明确告知的规则及实际订单记录为准。退款、争议或结算调整应说明原因及依据，不得任意扣减依法取得的收益。提交或批准提现不等于实际到账。\n八、注销与争议\n您可以通过上述邮箱或客服申请注销，平台核验身份并协助处理未完成订单、账户资金及争议，不设置不合理障碍。注销涉及的信息处理见隐私政策。\n争议可先协商，协商不成可依法投诉、申请调解或向有管辖权的人民法院起诉。本协议不排除或限制消费者法定权利，与法律强制性规定不一致的，以法律为准。\n九、更新\n协议重要变更应显著提示并依法取得必要同意，不以新规则追溯减损已经成立订单的合法权益。','',0,NULL,NULL,'{}',1,'active','2026-09-16 13:01:12','2026-09-16 13:05:36');
INSERT INTO `club_content` (`id`, `content_type`, `scene`, `title`, `subtitle`, `image`, `body_text`, `target_url`, `popup_enabled`, `start_at`, `end_at`, `style_json`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (8,'document','privacy','隐私政策','个人信息保护说明','','品奢电竞隐私政策\n版本日期：2026年9月10日；生效日期：本政策正式公布之日。\n一、处理者与联系方式\n个人信息处理者为绵阳市涪城区品奢电竞科技网咖(个人独资)。隐私权利申请和投诉邮箱：m19915375856@163.com。\n本政策说明个人信息处理目的、范围和权利行使方式。具体授权结合实际功能提示进行，不以同意本政策代替所有单独授权。\n二、信息种类与用途\n注册登录：处理账号UID、微信登录标识、登录凭证及必要登录记录，用于识别账号、保持登录和保障安全。设置手机号账号或订单联系时，处理您填写或经微信授权提供的手机号；设置密码时处理相应密码验证信息。\n资料与互动：处理您主动设置的昵称、头像、性别、生日、城市及收藏、评价、通知偏好。非履约必要的资料不应作为浏览公开内容的必要条件。\n订单履行：处理商品规格、订单编号、游戏ID、游戏昵称、联系人、联系电话、备注、服务状态、评价和售后材料，用于下单、联系、履约及争议处理。请勿在备注或图片中提交无关敏感信息或他人隐私。\n支付与结算：处理订单金额、支付方式、交易编号及状态、余额与资金流水、退款和提现记录，用于交易、对账和结算。微信支付由相应支付服务提供方处理；不要向客服提供支付密码、银行卡密码或验证码。\n身份认证及打手申请：处理主动提交的真实姓名、身份证号码、联系电话、服务介绍及必要申请材料，用于认证及入驻审核。已有认证资料可能用于后续入驻审核。身份证号码属于敏感个人信息，泄露或滥用可能影响身份和财产安全。提交前单独说明并取得同意；拒绝后不提交本次认证或申请，不影响不依赖该信息的公开浏览功能。记录同意场景、版本及时间用于证明授权。\n图片与语音：处理您主动选择或录制的头像、售后图片、服务介绍语音。调用相机、麦克风或保存图片等权限时由您决定是否授权。\n必要日志：为故障排查和安全防护处理必要IP地址、请求时间、接口访问和异常记录。\n三、权限选择\n您可拒绝与当前功能无关的权限。拒绝必要信息可能使对应功能无法完成，不应阻止不依赖该信息的功能。可在微信相关设置管理权限，撤回不影响撤回前合法处理，但可能影响后续对应功能。\n四、提供、公开与第三方处理\n我们不出售个人信息。为履约，仅向负责订单的服务人员提供必要游戏资料、联系方式及订单内容，不向普通用户公开身份证号码、密码或支付凭证。\n服务人员对外展示的昵称、头像、性别、年龄、城市、介绍、语音及接单状态，应以其主动提交并确认公开的资料为基础。\n微信平台相关服务：微信登录使用登录凭证及账号标识；手机号授权使用您确认授权的手机号相关信息；具体处理以微信功能页面及相应隐私告知为准。\n微信支付相关服务：支付、退款及适用的资金处理使用订单、金额、交易标识、状态和必要收款信息；具体以相应支付或收款页面的告知为准。平台不因您同意本政策而取得支付密码。\n技术服务：部署、存储和传输服务涉及服务器端信息处理。委托服务方时限定处理目的和范围并履行必要监督，不允许擅自另作他用。\n需要向其他独立处理者提供个人信息的，依法事先告知接收方、目的、信息种类等并在需要时取得单独同意。新增第三方或改变处理范围时更新相应告知，不用本政策作无限授权。\n五、保存与保护\n仅在实现目的所必要的期限内保存，法律对交易、财务等记录另有要求的依法保存。处理目的已实现、信息不再必要或符合其他删除条件时，依法删除或匿名化；依法暂不能删除的，仅作必要保存和安全保护。\n采取与风险相适应的访问控制、权限管理、传输保护及备份措施。发生安全事件时依法补救，并履行通知和报告义务。\n六、权利申请与注销受理\n可通过资料设置或联系邮箱申请查阅、复制、更正、补充、删除信息、撤回同意、注销账号及了解处理规则。实名资料如需更正，可联系人工核实，不因页面不能直接修改而拒绝受理。\n邮件请说明申请事项和账号UID或便于核对的账号信息；不要直接发送完整身份证照片、密码或验证码。平台按必要范围核验身份，告知处理结果；不能满足申请的说明理由。\n注销通过客服或邮箱人工受理，不表示已有自动注销按钮。平台协助结清未完成订单、余额、提现和争议事项，不设置不合理障碍；注销后除依法应保留的信息外，依法删除或匿名化。\n七、未成年人\n本平台仅面向年满18周岁人员，不向未成年人开放注册、购买或入驻。发现未成年人使用或提交信息，可通过邮箱联系，平台核实后停止相应服务并依法处理信息、订单及款项。本条不表示已经对所有用户自动完成年龄核验。\n八、更新\n处理目的、种类或提供范围发生重要变化时，显著告知并依法取得必要同意。疑问及权利申请请联系 m19915375856@163.com。','',0,NULL,NULL,'{}',1,'active','2026-09-16 13:01:12','2026-09-16 13:05:36');
INSERT INTO `club_content` (`id`, `content_type`, `scene`, `title`, `subtitle`, `image`, `body_text`, `target_url`, `popup_enabled`, `start_at`, `end_at`, `style_json`, `sort_no`, `status`, `created_at`, `updated_at`) VALUES (9,'document','filing','备案资质','平台资质说明','','备案与经营资质信息以后台最新配置为准。','',0,NULL,NULL,'{}',1,'active','2026-09-16 13:01:12','2026-09-16 13:01:12');
/*!40000 ALTER TABLE `club_content` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

